//cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

//charge
export const SUBMIT_CHARGE = 'SUBMIT_CHARGE';
export const SUBMIT_CHARGE_ERROR = 'SUBMIT_CHARGE_ERROR';
export const SUBMIT_CHARGE_SUCCESS = 'SUBMIT_CHARGE_SUCCESS';

export const GET_PRICE = "GET_PRICE";
export const GET_PRICE_SUCCESS = "GET_PRICE_SUCCESS";
export const CHECKOUT = 'CHECKOUT';

//user
export const SAVE_ORDER = 'SAVE_ORDER';
export const SEND_MESSAGE = "SEND_MESSAGE";


