//UI
export const UI_MODAL_OPEN = "UI_MODAL_OPEN";
export const UI_MODAL_CLOSE = "UI_MODAL_CLOSE";


// Charge
export const SUBMIT_CHARGE = "SUBMIT_CHARGE";
export const CHARGE_SUBMIT_CHARGE_SUCCESS =
  "CHARGE_SUBMIT_CHARGE_SUCCESS";
export const CHARGE_SUBMIT_CHARGE_ERROR =
  "CHARGE_SUBMIT_CHARGE_ERROR";